services:
  app:
    build: .
    container_name: f104-app
    ports:
      - "8080:8080"   # backend dostępny na localhost:3500
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    #command: ["npm", "run", "start"]  # start produkcyjny
    command: ["npm", "run", "dev"] # odkomentuj dla dev z nodemon

  mongo:
    image: mongo:6.0
    container_name: f104-mongo
    ports:
      - "27018:27017"   # Mongo dostępne w Compass na localhost:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: